### ISSUE TITLE
Squeezer 1.4 is broken for images

### ISSUE THREAD

**Issue by SeeBenClick** [drkameleon/squeezer#1]
Squeezer 1.4 is still broke. Are you fixing the problem with the squeezer interface that was reported several weeks ago using the web form on your website? I've sent you screen shots and file samples and then I haven't heard back for weeks. Looking at the logs it is the interface at fault. Running the command line squeezer generates in terminal will properly shrink images. Actually using squeezer results in 0 byte files on OS X 10.11

**Comment by drkameleon** [comment]
Hi,

I know what you're saying and I've not forgotten about it. I know it's taken (much) more time than I myself initially suspected, but I'm doing my best to bring the next release up as soon as possible. :)

**Comment by drkameleon** [comment]
Issue fixed (at last!) as of the upcoming 1.7. :-)
